spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/boba_bliss?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=#manya@24

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=ThisIsVeryLongSecretKeyForBobaBlissJwtTokenSigning1234567890
app.jwt.expiration-ms=86400000